name: Continuous Integration

on:
  push:
    branches:
      - master
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-and-build:
    name: 'Test & build'
    runs-on: buildjet-4vcpu-ubuntu-2204
    timeout-minutes: 30

    steps:
      - name: 'Checkout the repository'
        uses: actions/checkout@v4

      - name: 'Setup Node.JS'
        uses: actions/setup-node@v4
        with:
          node-version: '20.18.3'

      - name: 'Cache dependencies'
        uses: buildjet/cache@v4
        with:
          path: |
            **/node_modules
            ~/.cache/ms-playwright
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/yarn.lock') }}

      - name: 'Install dependencies'
        run: |
          yarn install --frozen-lockfile
          yarn playwright install --with-deps

      - name: 'Run tests'
        run: yarn test

      - name: 'Check code formatting'
        run: yarn format:check

      - name: 'Run linter'
        run: yarn lint

      - name: 'Build package'
        run: yarn build
